# Generated by Django 3.2.4 on 2021-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('headlines', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=140)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
